// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';

// static user
export const SET_STATIC_USER = 'SET_STATIC_USER';
export const LOADING_STATIC_USER = 'LOADING_STATIC_USER';
export const STOP_LOADING_STATIC_USER = 'STOP_LOADING_STATIC_USER';
export const LIKE_STATIC_USER_POST = 'LIKE_STATIC_USER_POST';
export const UNLIKE_STATIC_USER_POST = 'UNLIKE_STATIC_USER_POST';

// UI reducer types
export const SET_ERRORS = 'SET_ERRORS'
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';

// data reducer types
export const UPLOAD_POST = 'UPLOAD_POSTS';
export const SET_POSTS = 'SET_POSTS';
export const SET_DATA_ERRORS = 'SET_DATA_ERRORS';
export const CLEAR_DATA_ERRORS = 'CLEAR_DATA_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_DATA = 'STOP_LOADING_DATA';
export const LIKE_POST = 'LIKE_POST';
export const UNLIKE_POST = 'UNLIKE_POST';
export const DELETE_POST = 'DELETE_POST';

// friends reducer types
export const SET_SUGGESTED_FRIENDS = 'SET_SUGGESTED_FRIENDS';
export const LOADING_SUGGESTED_FRIENDS = 'LOADING_SUGGESTED_FRIENDS';
export const STOP_LOADING_SUGGESTED_FRIENDS = 'STOP_LOADING_SUGGESTED_FRIENDS';
export const ADD_FRIEND = 'ADD_FRIEND';
export const CANCEL_REQUEST = 'CANCEL_REQUEST';
export const UNFRIEND = 'UNFRIEND';
export const CONFIRM_FRIEND = 'CONFIRM_FRIEND';
export const SET_FRIENDS_ERRORS = 'SET_FRIENDS_ERRORS';
export const CLEAR_FRIENDS_ERRORS = 'CLEAR_FRIENDS_ERRORS';
